In [ ]:

import numpy as np
np1=np.arange(100,125).reshape(5,5)
print(np1)

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]


In [2]:
!pip install pandas

  Using cached pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Using cached pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl (10.0 MB)


In [4]:
import pandas as pd
df1=pd.DataFrame(np1,index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4','col5'])
print(df1)

      col1  col2  col3  col4  col5
row1   100   101   102   103   104
row2   105   106   107   108   109
row3   110   111   112   113   114
row4   115   116   117   118   119
row5   120   121   122   123   124
